spring:
  application:
    name: pets-service
  config:
    import: optional:file:.env[.properties]
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:postgresql://localhost:7434/pets_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db-pets

server:
  port: 8082

app:
  messaging:
    exchange-name: "x.petshop"
    request-queue-name: "q.pets.requests"
    request-routing-key: "rk.pets.requests"
    reply-routing-key: "rk.gateway.replies"
