name: Build

on:
  push:
  pull_request:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.event_name == 'pull_request' }}

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Clean build and tests
        run: ./gradlew --no-daemon clean build
        env:
          CI: true

      - name: Upload test results (XML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: |
            **/build/test-results/test/*.xml
          if-no-files-found: warn

      - name: Upload test report (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: |
            **/build/reports/tests/test
          if-no-files-found: warn
