name: Build

on:
  push:
  pull_request:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.7
          cache-read-only: ${{ github.event_name == 'pull_request' }}

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Verify Gradle version
        run: |
          echo "System Gradle version:"
          gradle --version
          echo "Wrapper Gradle version:"
          ./gradlew --version

      - name: Clean build and tests
        run: |
          if ./gradlew --no-daemon clean build; then
            echo "Build successful with wrapper"
          else
            echo "Wrapper failed, trying system Gradle"
            gradle --no-daemon clean build
          fi
        env:
          CI: true

      - name: Upload test results (XML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: |
            **/build/test-results/**/*.xml
          if-no-files-found: warn

      - name: Upload test report (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: |
            **/build/reports/tests/**
          if-no-files-found: warn
